services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  web:
    image: web
    build: ./web
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 8001:8080

