services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
  cron:
    image: cron
    build: ./cron
    environment:
      C_FORCE_ROOT: true
      POCKETBASE_URL: 'http://backend:8080'
      REDIS_URL: 'redis://redis'
      ADMIN_EMAIL: 'admin@rize.anonaddy.com'
      ADMIN_PASSWORD: 'Tameness3,Swaddling,Immovable,Open'
  web:
    image: web
    build: ./web
    environment: {}

