# Generated by Django 5.1.1 on 2024-09-11 04:07

from django.db import migrations, models
import AMS


class Migration(migrations.Migration):

    dependencies = [
        ("AMS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="ntfy_topic",
            field=models.CharField(
                default=AMS.models.random_string, max_length=32, unique=True
            ),
        ),
    ]
