# Generated by Django 5.1.1 on 2024-09-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AMS", "0002_student_ntfy_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ntfy_topic",
            field=models.CharField(
                default="E6IvfbvFkfvKCpJv", max_length=32, unique=True
            ),
        ),
    ]
