# Generated by Django 5.1.1 on 2024-09-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AMS", "0003_attendance_last_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="last_run",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
