# Generated by Django 5.1.1 on 2024-09-11 16:26

from django.db import migrations, models
import AMS
from AMS.models import Student

def gen_ntfy_topics(apps, schema_editor):
    for row in Student.objects.all():
        row.uuid = AMS.models.random_string()
        print(row.uuid)
        row.save(update_fields=["ntfy_topic"])


class Migration(migrations.Migration):

    dependencies = [
        ("AMS", "0004_alter_attendance_last_run"),
    ]

    operations = [
        migrations.RunPython(gen_ntfy_topics),
    ]
