# Generated by Django 5.1.1 on 2024-09-11 16:26

from django.db import migrations, models
import AMS

class Migration(migrations.Migration):

    dependencies = [
        ("AMS", "0005_student_ntfy_topic_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ntfy_topic",
            field=models.CharField(
                default=AMS.models.random_string, max_length=32, unique=True
            ),
        ),
    ]
