# Generated by Django 5.1.1 on 2024-09-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AMS", "0006_student_ntfy_topic_alter"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="subject_details",
            field=models.JSONField(null=True),
        ),
    ]
